name: Test
on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Install dependencies packages for linux
        if: runner.os == 'Linux'
        run: sudo apt-get install ocl-icd-opencl-dev opencl-headers
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Run cl-info
        run: go run ./cmd/cl-info/
      - name: Test with the Go CLI
        run: go test
